### ISSUE TITLE
Basic features

### ISSUE THREAD

**Issue by kameronton** [SEM1INFOENS/multiplanner#1]
We should implement basic features, such as (list could be updated):

- [x] set up the main framework (Django)
- [x] set up testing framework
- [x] set up CI
- [x] create a new database
- [x] create users
- [ ] basic web-interface
- [x] authentication

**Comment by dbaelde** [comment]
Am I right that the application still has no web interface ? If so, what's your plan ? If not, please add a line about this in the README.
