### ISSUE TITLE
Sitting arrangement

### ISSUE THREAD

**Issue by kameronton** [SEM1INFOENS/multiplanner#10]
For an event, the organizer can provide a number of tables with their respective capacities. The application should propose a sitting arrangement for all the invitees, based on the secret relationship ratings, and a notion of optimality that should be specified clearly. The organizer may provide its own relationship rating between people if he wishes.

**Comment by Z-ephyr** [comment]
It is possible to reuse existing technologies.

**Comment by MaloPerez** [comment]
Using linear programming, and solving using PyGLPK.
Mathematical formulation of the sitting problem comming soon.

**Comment by Z-ephyr** [comment]
The secrete marks will be between -10 and 10, if this is not ok let @PierreGtch and me know !

**Comment by dbaelde** [comment]
@TarteAuMaroilles @MaloPerez any news here ?

**Comment by MaloPerez** [comment]
I have not been able to install the pyglpk module, however I have coded all of it using the pyglpk documentation. Until I find a way to successfully install glpk, I cannot start to test. It's what I'm hoping to figure out today.

**Comment by MaloPerez** [comment]
Finished writing the algorithm in C using swiglpk, tested in C.
Anyone knows a way to use a C function in python ? Have been trying with cython and ctypes without any sucess.

**Comment by dbaelde** [comment]
I'm worried that the path you've chosen involves unnecessary complications. It should be possible to install one of the recent python linear programming libs, or at least export the problem as a file to be passed to a binary solver...

**Comment by MaloPerez** [comment]
Would you advise me to abandon trying to use C then ? And try using Pulp (since pyglpk doesn't work) ?

**Comment by MaloPerez** [comment]
Manged to make the interface between C and python using ctypes.

**Comment by Z-ephyr** [comment]
Hmm I don't know about this small window opening thing (@kameronton has used them, but I have never done do). If you wanted to do it with new page each time, I would suggest:
1. Create a view asking for the number of tables (with a form that you create by hand I think)
2. Then redirect to a new page (created in a different view) whose template uses a for loop to create a form with the right number of tables
Idk if this helps or if it is too late

**Comment by Z-ephyr** [comment]
@DuncanSussfeld ^

**Comment by DuncanSussfeld** [comment]
Yes, it's in agenda/sit.py
Takes an event and a list of sizes of tables as input

**Comment by PierreGtch** [comment]
For the GUI I tried to create a variable number of integer input fields but I diden't manage to do it

So I created a new branch : https://github.com/SEM1INFOENS/multiplanner/tree/sitting

And used `django-formset-bootstrap` : https://github.com/mbourqui/django-formset-bootstrap

The goal is to have something like this : 

![alt text](https://whoisnicoleharris.com/assets/img/formset-animation.gif)

**Comment by PierreGtch** [comment]
from : http://www.lsv.fr/~baelde/gl/eval.html

### Sitting arrangement
#### Score: 2.5 (★★)

The main algorithm is present and convincing. It is however insufficiently documented, and its integration is too rough, notably lacking on error cases and sometimes raising an exception.

The requirements are not completely satisfied: the optimized quantity is not explicitly stated; a user cannot override relationship ratings for a sitting arrangement.

Note that randomized testing could have been possible here (and probably in other places) e.g. by generating possible problems, running the optimizer, and checking that it finds a solution with a greater or equal score.

**Comment by Z-ephyr** [comment]
@MaloPerez Where are we on this issue?

**Comment by MaloPerez** [comment]
I documented more, took care of adding error cases. I stated exactly the quantity optimized. The only missing is the user overidding relationship ratings, but I'm having a lot of trouble with that, so I might not do it.
