### ISSUE TITLE
Index Page recalculate a correct balance with the multiple currency variation

### ISSUE THREAD

**Issue by Kessaye** [SEM1INFOENS/multiplanner#101]

**Comment by PierreGtch** [comment]
@Kessaye dans 95a8485 j'ai ajouté à ton code la monnaie par défaut des utilisateurs mais la fonction `balance_of_user` était cassée, elle retourne toujours `0, 0`...

**Comment by PierreGtch** [comment]
@Kessaye finalement `balance_of_user` marche depuis la page web mais pas dans les tests, elle retourne toujours `0,0`..
je les ai mis à jour dans c4b6386a54f0b6ca6286aca0148c0336a71c17a3

les transactions sont sûrement crées différemment dans les tests et depuis l'interface

**Comment by Kessaye** [comment]
@PierreGtch Vu que ca marche la fonciton, je close cet issue ou pas ?

**Comment by Z-ephyr** [comment]
Corrige les tests d'abord :)

**Comment by Z-ephyr** [comment]
@DuncanSussfeld got a similar problem : a transaction created had always amount 0 in the test...
