### ISSUE TITLE
Index page is broken

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#110]
I don't know if this issue is already dealt with in another issue...

**Comment by Z-ephyr** [comment]
```column accounting_transaction.calculated does not exist
LINE 1: ...unt_currency", "accounting_transaction"."amount", "accountin...```
This breaks nearly everything

**Comment by Z-ephyr** [comment]
-

**Comment by PierreGtch** [comment]
mabe just reset the db @Z-ephyr

**Comment by Z-ephyr** [comment]
Hmm I tried already twice this time I'll delete the migrations as well

**Comment by Z-ephyr** [comment]
I have errors on heroku as well

**Comment by Z-ephyr** [comment]
Refreshing the page solved it ^^

**Comment by Z-ephyr** [comment]
But I have a problem on agenda
<img width="1440" alt="screenshot 2019-01-15 at 19 41 53" src="https://user-images.githubusercontent.com/43679368/51201929-aaa14900-18fd-11e9-990f-36ec17b36697.png">

**Comment by PierreGtch** [comment]
that's wierd, did you install the requirements ?

**Comment by Z-ephyr** [comment]
Normally I have
I am sure I have installed jsonify

**Comment by Z-ephyr** [comment]
Ok it works now! Thanks for your patience :)
