### ISSUE TITLE
bug group invitations + balances 

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#117]
@Kessaye I added group invitations in 0f61fef5d677044e301289434580b27db86dd7da but when a user accept/decline an invitation or quit a group, it doesent uses the form  so balances are not created and the page breaks...
The  functions to acept, decline and quit are in `group.views.nvitation_answer_group` 
https://github.com/SEM1INFOENS/multiplanner/blob/0f61fef5d677044e301289434580b27db86dd7da/groups/views.py#L153

Can you take a look and merge when it's done ?

**Comment by Kessaye** [comment]
@PierreGtch  I think I solved it but the problem is that we cannot see the invitations from others.
