### ISSUE TITLE
Platform

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#12]
Continuous integration should be used to systematically build and test your software at least after each commit in master

**Comment by dbaelde** [comment]
CI is what's left to do for the "Platform" requirement from the course webpage. Could we perhaps rename this issue to "Platform"? I'd also suggest using a title or a github label that helps to identify this as a requirement for the course.

**Comment by dbaelde** [comment]
This is good enough as far as I'm concerned, feel free to close this issue.

**Comment by Z-ephyr** [comment]
- [ ] Pylint in CI : code's mark should not be under 3 or 5
