### ISSUE TITLE
Resolution branch does not build

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#123]
@Kessaye I am merging notifications branch right now. As it depends also in the resolution branch, there is the same bug that makes the build fail. Where are we on this matter?

**Comment by Kessaye** [comment]
Can you be more precise please? If you're talking about the issue #112 it is kameronton that solved it on the master branch

**Comment by Kessaye** [comment]
@Z-ephyr the tests for resolution are not up to date, @DuncanSussfeld  seems that he's writing the tests.

**Comment by Z-ephyr** [comment]
I don't think he is... Il s'occupe déjà du reste et ça fait beaucoup
Je ne comprends pas vraiment... Il reste du travail sur la branche résolution ou pas ? En tous cas, si les tests sont obsolètes, il faut les enlever.

**Comment by DuncanSussfeld** [comment]
J'ai focus sur les parties où je comprenais le code (aka pas grand chose je sais, mais en particulier pas resolution). Désolé :/
