### ISSUE TITLE
ICS events url refer to localhost

### ISSUE THREAD

**Issue by Sabotaz** [SEM1INFOENS/multiplanner#125]
When downloading my calendar, the links in the url parts are `http://localhost:8000/agenda/calendar.ics`.

It could be nice to have the server address related to the event instead like `https://domain.com/agenda/event/{event_number}`.

**Comment by PierreGtch** [comment]
it's supposed to be used on multiplanner.herokuapp.com/

**Comment by Sabotaz** [comment]
I was doing an export from this server. 
I think it is the url in this file who is not parameterized:

https://github.com/SEM1INFOENS/multiplanner/blob/master/agenda/templates/calendar.ics

**Comment by Z-ephyr** [comment]
<img width="1440" alt="screenshot 2019-01-18 at 14 50 49" src="https://user-images.githubusercontent.com/43679368/51390775-84afba80-1b30-11e9-957d-27aaf972073d.png">
I do not have this bug...
