### ISSUE TITLE
The project must be accessible by teachers and other students.

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#13]
- [x] Teachers
- [x] Students

**Comment by Z-ephyr** [comment]
- [ ] Teachers
- [ ] Students

**Comment by dbaelde** [comment]
This being a public github, it is accessilbe to teachers. Hence the issue can be closed as far as I'm concerned.

**Comment by Z-ephyr** [comment]
I was waiting for you to join because Charlie told us you did not manage to see the invitation. But indeed now it is not needed anymore.
