### ISSUE TITLE
Optimal meetings

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#15]

**Comment by kameronton** [comment]
Check this: https://pythonhosted.org/PuLP/

**Comment by TarteAuMaroilles** [comment]
Initiation to Pulp for integer programming: https://blog.remix.com/an-intro-to-integer-programming-for-engineers-simplified-bus-scheduling-bd3d64895e92
Example to look into for equivalence of all results: https://pythonhosted.org/PuLP/CaseStudies/a_sudoku_problem.html

**Comment by dbaelde** [comment]
@TarteAuMaroilles @MaloPerez any news on this part of the project ?

**Comment by DuncanSussfeld** [comment]
# Issue put on hold until end of first phase

**Comment by DuncanSussfeld** [comment]
Check Constraint programming solutions:
https://fr.wikipedia.org/wiki/Programmation_par_contraintes  for model explanation
https://labix.org/python-constraint  for potential use in implementation

**Comment by Z-ephyr** [comment]
Given up
