### ISSUE TITLE
New methods for main user page

### ISSUE THREAD

**Issue by kameronton** [SEM1INFOENS/multiplanner#24]
- [x] Random list of six friends (as [User])

- [x] Sum of "positive" and "negative" transactions for user

- [x] List of transactions in user's related groups and events (the most complicated, I suppose)

**Comment by Z-ephyr** [comment]
I am having a lot of trouble with the first method... User is a Django model and we need to modify it.

I found this https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#proxy which would give the following code.

```python
'''Models for the presentation app'''

from random import shuffle
#from django.db import models
from django.contrib.auth.models import User
from relationships.models import Friendships

class Person(User):
    '''This is an extension of the User Model using a Proxy Model
    https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#proxy'''
    class Meta:
        proxy = True

    def six_random_friends(self):
        '''Returns a random list of six friends'''
        friendlist = Friendships.objects.get(user=self).friend_list

        if len(friendlist) < 6:
            return friendlist

        return shuffle(friendlist)[:6]
```
But then we would need to transform every User into a Person. What do you think of this ?

**Comment by PierreGtch** [comment]
I think it would be simpler to just create functions that take a User as input

**Comment by Z-ephyr** [comment]
Oh :o Yes indeed it seems much simpler.
Where am I supposed to put such a function ?

**Comment by kameronton** [comment]
I think we should change purpose of "presentation" app to "users" app, so it will show user pages in general
So, you can put it in this app

**Comment by PierreGtch** [comment]
You can create a new file `file.py` and import in views with `from .file import *`

**Comment by Z-ephyr** [comment]
Ok, thank you !

**Comment by Z-ephyr** [comment]
Ok, the first method is done ! :)

**Comment by Z-ephyr** [comment]
@Kessaye I need your resolution code to do method 2. Can you please explain to me how to use it ? From what I understand, I call resolution on the group and with the corresponding balance function. Is that correct ?
Also, could you please modify it so that instead of returning a 3-tuple it returns a Transaction ? (You can use ```python Transaction.create_new(motive = ..., payer = ..., amount = ..., beneficiaries = ...)```. For the motive you could just put "Repayment") From what I see in your code, I think I can do it but it may be better, as you're the code the designer, if you're the one who makes changes.

**Comment by Z-ephyr** [comment]
@kameronton I am not sure I understand what you want for the third method. A few options spring to my mind, but they might all be wrong.

For each group/event in which the user is ;
      Option A: if resolution indicates that there is a transaction that the user has to do or has to receive;
      Option B: if resolution indicates that there is a transaction that the user has to do ;
                       Option 1: the repayment transactions that are left to be done are shown ;
                       Option 2: all the transactions the user made are shown (this may include some repayments already done );
                       Option 3: all the repayment transactions the user made are shown ;
                       Option 4: all the transactions from whom the user beneficiates are shown (this may include some repayments already done);
                       Option 5: all the repayment transactions from whom the user beneficiates are shown.

A and B are exclusive, but you can choose several numbers. Let me know what you would want!

**Comment by Z-ephyr** [comment]
I add this label because we need these methods to complete one of the course requirement (as it is part of a basic user interface).

**Comment by Z-ephyr** [comment]
So you would like the five last transactions the user made / benefited from ?

**Comment by DuncanSussfeld** [comment]
Completed, closing the issue.
