### ISSUE TITLE
Event edition

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#25]
When we edit an event and save it, a new one is created but we don't want that !

**Comment by Z-ephyr** [comment]
Form should precise the desired format for the time and time_end fields

**Comment by Z-ephyr** [comment]
@PierreGtch I get the impression that, when one modifies an event, they becomes the `creator` of the event, which is strange.

**Comment by PierreGtch** [comment]
@Z-ephyr yes but in fact I don't know why we need this `creator` field
Mabe we could just de delete it

**Comment by Z-ephyr** [comment]
Found the problem! In `edit_event.html` there is the line
```html <form action="{% url 'new-event' %}" method="post">
```

**Comment by Z-ephyr** [comment]
@PierreGtch I don't know either... But I guess that is interesting to know who created the event. In any case, it shouldn't change when the event is edited.

**Comment by PierreGtch** [comment]
@Z-ephyr but the `create_event` view also uses the template `edit_event.html`
So we could either in this template take the action url from the context or create two different templates

**Comment by Z-ephyr** [comment]
Oups! Indeed I broke `create_event`
Or we could have one view for both tasks

**Comment by PierreGtch** [comment]
I will try to fix that

**Comment by PierreGtch** [comment]
@Z-ephyr minimal effort :  `8 additions and 4 deletions` !

**Comment by Z-ephyr** [comment]
@PierreGtch Haha nice !
