### ISSUE TITLE
GUI to set a secrete mark

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#27]

**Comment by PierreGtch** [comment]
@MaloPerez, @DuncanSussfeld did you do something for the secrete marks ? If you want I can take it

**Comment by MaloPerez** [comment]
We were going to meet up tomorrow morning to try to figure it out !

**Comment by PierreGtch** [comment]
Dac bon courage !

**Comment by PierreGtch** [comment]
@DuncanSussfeld @MaloPerez vous y arrivez ?

**Comment by DuncanSussfeld** [comment]
on a tous les 2 cette erreur on sait pas quoi faire pour la résoudre, jusque là nos tâches c'était du backend donc pas grave mais là du coup c'est frontend donc c'est plus problématique 
![image](https://user-images.githubusercontent.com/43679786/49141553-27994480-f2f7-11e8-8538-c768b44627ef.png)

**Comment by PierreGtch** [comment]
vous avez fait `python3 manage.py migrate --run-syncdb` ?

si vous y arrivez vraiement pas, vous pouvez créer une autre branche et push dessus. C'est pas grave si la nouvelle en marche pas

**Comment by DuncanSussfeld** [comment]
En quoi ça résoudrait le truc de créer une autre branche ?

**Comment by PierreGtch** [comment]
comme ça tout le monde peut voir le proobleme et aider

**Comment by DuncanSussfeld** [comment]
mais on est à jour sur les derniers push donc je vois pas en quoi ça changerait ?

**Comment by PierreGtch** [comment]
Vous vous en sortez ? je peux le faire en 20 min sinon

**Comment by DuncanSussfeld** [comment]
On se voit ce soir pour le faire normalement, mais si tu veux t'en débarrasser ou que ça te bloque vas-y
Il faut aussi qu'on crée de quoi faire le sitting arrangement

**Comment by Kessaye** [comment]
Problem when setting a mark as a float (1.00000 , 2.0, ...)
