### ISSUE TITLE
Group and event pages

### ISSUE THREAD

**Issue by kameronton** [SEM1INFOENS/multiplanner#31]

**Comment by PierreGtch** [comment]
> When creating an event, a group should be created.
> Should the creator of the event be automatically added to it? If it is not automatic, there should be a checkbox when creating an event "I will attend this event", no?

The creator of the event doesen't have to attend it. And yes for the checkbox ! I will do it 

> The attendees should be shown on the page of the event.

I will also do it !

**Comment by PierreGtch** [comment]
After all, the checkbox seems complicated.. For now the creator will have to invite himself and accept the invite

**Comment by Z-ephyr** [comment]
In the agenda page, events you attend should not be listed in "events you are invited to".

**Comment by PierreGtch** [comment]
> In the agenda page, events you attend should not be listed in "events you are invited to".

Indeed, I will fix it

**Comment by PierreGtch** [comment]
> > In the agenda page, events you attend should not be listed in "events you are invited to".
> 
> Indeed, I will fix it

Fixed in 93c59c6
