### ISSUE TITLE
Friend requests

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#33]
We can now send friendship requests 59eb0cf4a73665966d606c37cd9651bffaf81b6 (sorry for the commit title I don't know what happened)

 - But it is still unclear what should we do if a user declines a friendship request. Is the other user ban-listed forever ? can he resend invites ? is he notified or should we lie and say that his request is still waiting ?
 - Also the way I made the buttons is such that when we reload the page, a new POST request is sent...
There must be better ways

**Comment by Z-ephyr** [comment]
We have not created ban-list, but we could. However, I think declining a friend invitation is not the same as ban-listing. (Moreover, it is good that they can resend an invitation in case of misclick. But it would be good to have a ban-list as well to avoid harassment).
To me, when someone declines the friendship request, the other person is not notified but the invitation disappears from the list of pending ones.

**Comment by Z-ephyr** [comment]
What we decided : 
* when somebody receives an invitation, they have the choice between "accept", "decline" and "ban"
* whatever the choice, the invited person is not in the invited_list anymore
* if they chooses "accept", the invitor receives a notification, the invitee is now in the friend list
* if they chooses "decline", nothing else happens
* if they chooses "ban", the invitor is now in the ban_list of the invited ; they cannot invite again this person
