### ISSUE TITLE
Main page 

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#37]
Link the backend methods to the main page and make the links working

**Comment by PierreGtch** [comment]
```html
 <span class="sr-only">(current)</span>
```
@kameronton what does that means in the base_template ?

**Comment by kameronton** [comment]
Nothing, actually

**Comment by PierreGtch** [comment]
ok, I remove it

**Comment by PierreGtch** [comment]
- [ ] define `__str__` functions dor `Group` and `Transaction` models

**Comment by PierreGtch** [comment]
-[ ] when the browser page is not large enough or on mobile, the links in navbar and the search bar disepear
