### ISSUE TITLE
When we edit an event the attendees group is erased

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#40]

**Comment by PierreGtch** [comment]
If during the event edition we un-invite a user that already accepted the invite, we have a problem... 

What should happen then ?

**Comment by Z-ephyr** [comment]
You should not be able to uninvite them. But administrators should always have the possibility to uninvite persons who have not yet accepted or cancel the attendance of somebody who accepted.

**Comment by DuncanSussfeld** [comment]
Also the transactions seem to disappear upon edit

**Comment by Z-ephyr** [comment]
@PierreGtch Did you do it ? If not, I can take care of it

**Comment by PierreGtch** [comment]
No I didn't
