### ISSUE TITLE
Migrate db

### ISSUE THREAD

**Issue by PierreGtch** [SEM1INFOENS/multiplanner#48]
I added a field `Group.inEvent` but was not able to do the right migrations to the heroku db to create the column `groups_group.inEvent`.

So for now the heroku app is broken.

@kameronton do you know how to make the migrations ? If no we will have to delete the database

**Comment by kameronton** [comment]
I've tried several methods, it doesn't seem that it is possible to do it without deleting the DB.

**Comment by PierreGtch** [comment]
In fact with sqlite I think it is impossible https://docs.djangoproject.com/fr/2.1/topics/migrations/

**Comment by PierreGtch** [comment]
@kameronton @Z-ephyr @DuncanSussfeld @Kessaye @MaloPerez I deleted the database and created a new one
