### ISSUE TITLE
ICS export

### ISSUE THREAD

**Issue by kameronton** [SEM1INFOENS/multiplanner#5]
Calendars must be accessible as ICS, with authentication.

**Comment by Z-ephyr** [comment]
- On ajoute une URL en localhost pour qu'il puisse y avoir des actualisations
- On crée un template qui crée du ICS
- On crée une view qui envoie les données de l'événement et qui est sécurisée pour authentification

**Comment by Z-ephyr** [comment]
Left to do
- [ ] Loop for putting all the events in the ics file
- [ ] Take care of the date of the events (with change of model Event)
- [ ] Add an url for "feeding"

**Comment by Z-ephyr** [comment]
- [ ] give the right user to generate_calendar

**Comment by Z-ephyr** [comment]
- [ ] add a button to download on the agenda webpage

**Comment by PierreGtch** [comment]
@Z-ephyr that's the app we talked about yesterday :  https://github.com/llazzaro/django-scheduler

And I don't know if it helps but they create their feed like that :
https://github.com/llazzaro/django-scheduler/blob/develop/schedule/feeds/ical.py

**Comment by Z-ephyr** [comment]
One thing I could try: s'abonner depuis l'application calendar
