### ISSUE TITLE
Bug in resolution

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#65]
Sometimes, people can owe 7e-9€ to others...

**Comment by PierreGtch** [comment]
We can use the currency filter to display amounts nicely `{{
amount¦currency }}`
https://djangosnippets.org/snippets/552/

Or while we don't have currencies : `{{ amount¦intcomma }}`
https://docs.djangoproject.com/fr/2.1/ref/contrib/humanize/




Le ven. 14 déc. 2018 à 15:02, Duncan Sussfeld <notifications@github.com> a
écrit :
