### ISSUE TITLE
Some tests are not run

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#66]
When tests.py does not get 100% coverage, it is generally a bad sign
Note that
* it’s setUp not SetUp (cf accounting/tests.py)
* Be careful that two tests should not have the same name (cf presentation/tests.py)

**Comment by Z-ephyr** [comment]
@PierreGtch The first test called `test_latest_transactions` in `presentation/tests.py` does not run because it has exactly the same name as the following function. However, when one changes the name one realizes the test fails. I have tried to debug it but I don't understand your function well.

**Comment by PierreGtch** [comment]
About 344d59a : 
The problems in `n_transactions_of_user` in /presentation/tests.py was that thansactions had the same creation date so the `order_by('date')` diden't work.
Also `n_transactions_of_user` returns a list of tupples containing a transaction ald other informations. Not just a transaction list
