### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by kameronton** [SEM1INFOENS/multiplanner#8]
The tool should propose solutions to balance the account: optimizing either the total number of transactions, or the maximum number of transaction per user.

**Comment by Z-ephyr** [comment]
Algorithmic part

**Comment by Kessaye** [comment]
Problems in float representation (is it due to python or the mathematical representation of float on computer):

>>> -0.8-1.6+2.4
-4.440892098500626e-16
>>> 9.6 - 0.3 
9.299999999999999
