### ISSUE TITLE
Main page broken: NoReverseMatch: index.html

### ISSUE THREAD

**Issue by Kessaye** [SEM1INFOENS/multiplanner#80]
When creating a transaction in group and saving it, then saving the transaction_details, getting back to the main pages breaks the site.
I don't think it is a too hard issue to solve (has to do with the urls) but it is essential.

**Comment by PierreGtch** [comment]
the transaction  details url name changed in 86198d33655cd756450f35ec0796b4bc837a4194
I am fixing it
