### ISSUE TITLE
"Group members" in events

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#91]
This should be "event attendees"
<img width="709" alt="screenshot 2019-01-11 at 14 51 36" src="https://user-images.githubusercontent.com/43679368/51037414-7140a480-15b0-11e9-96b5-f87bb51b9bf0.png">

**Comment by Z-ephyr** [comment]
Moreover, there is a spellink mistake

**Comment by Kessaye** [comment]
Closed in commit 23223e6
