### ISSUE TITLE
When creating an event, the invited persons all become admins

### ISSUE THREAD

**Issue by Z-ephyr** [SEM1INFOENS/multiplanner#93]
Maybe it's only the invited persons that are app-admin ?

Afterwise it is possible to edit to change the admin list, but it is still a problem

**Comment by PierreGtch** [comment]
Is it still topical ?

**Comment by Z-ephyr** [comment]
Right now creating a group bugs so it's hard to tell ^^

**Comment by kameronton** [comment]
nope, it is not
